apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-deployment
spec:
  selector:
    matchLabels:
      app: secrets
  replicas: 1
  template:
    metadata:
      labels:
        app: secrets
    spec:
      volumes:
        - name: secret-1
          secret:
            secretName: mysecret
      containers:
      - name: secrets-container
        image: busybox
        volumeMounts:
          - mountPath: /etc/secrets
            name: secret-1
        env:
          - name: AMIGOSCODE_SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret-from-file
                key: secret
        command:
          - "sleep"
          - "3600"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
